shell /usr/bin/zsh
kitty_mod ctrl+shift
hide_window_decorations yes

#FONT

font_family      DepartureMono Nerd Font
bold_font        auto
italic_font      auto
bold_italic_font auto
# BEGIN_KITTY_THEME

# Catppucci0
include current-theme.conf

# END_KITTY_THEME

#set font size
font_size 18

#set background opacity
background_opacity 0.90

#LAYOUT
enabled_layouts tall,*

#Set Window margin size
draw_minimal_borders yes
window_margin_width 5
window_border_width 5

#Background
#background_image ~/Pictures/judy2077.png
background_tint 0.90
background_tint_gaps 0

#Window management
map ctrl+shift+enter new_window
map ctrl+shift+q close_window
map ctrl+shift+left next_window
map ctrl+shift+right previous_window

#Cursor
cursor_shape block
cursor #4169E1
cursor_blink_interval 0
cursor_beam_thickness 1.5
cursor_trail 3
cursor_trail_decay 0.1 0.4
cursor_trail_start_threshold 2


background_blur 20
